-- WYGENEROWANE przez scripts/gen-seed.ts z src/data/mock – nie edytuj ręcznie.
-- Kody TERYT z assets/geo/gminy-index.geo (npm run geo:build); granice (boundary) uzupełnia import PRG (GUGiK).

insert into public.forest_regions (id, name) values
  ('puszcza-knyszynska', 'Puszcza Knyszyńska'),
  ('lasy-podlasia', 'Lasy Podlasia'),
  ('puszcza-bialowieska', 'Puszcza Białowieska')
on conflict (id) do nothing;

insert into public.gminy (id, teryt, name, voivodeship, forest_region_id, tile_row, tile_col) values
  ('wasilkow', '2002133', 'Wasilków', 'podlaskie', 'puszcza-knyszynska', 0, 2),
  ('czarna-bialostocka', '2002023', 'Czarna Białostocka', 'podlaskie', 'puszcza-knyszynska', 0, 3),
  ('dobrzyniewo-duze', '2002032', 'Dobrzyniewo Duże', 'podlaskie', 'puszcza-knyszynska', 0, 4),
  ('choroszcz', '2002013', 'Choroszcz', 'podlaskie', 'lasy-podlasia', 0, 5),
  ('zabludow', '2002143', 'Zabłudów', 'podlaskie', 'puszcza-knyszynska', 1, 1),
  ('juchnowiec-koscielny', '2002052', 'Juchnowiec Kościelny', 'podlaskie', 'lasy-podlasia', 1, 2),
  ('bialowieza', '2005022', 'Białowieża', 'podlaskie', 'puszcza-bialowieska', 1, 3),
  ('dubicze-cerkiewne', '2005052', 'Dubicze Cerkiewne', 'podlaskie', 'puszcza-bialowieska', 1, 4),
  ('czyze', '2005042', 'Czyże', 'podlaskie', 'puszcza-bialowieska', 1, 5),
  ('kleszczele', '2005073', 'Kleszczele', 'podlaskie', 'puszcza-bialowieska', 1, 6),
  ('szudzialowo', '2011102', 'Szudziałowo', 'podlaskie', 'puszcza-knyszynska', 2, 0),
  ('sokolka', '2011083', 'Sokółka', 'podlaskie', 'puszcza-knyszynska', 2, 1),
  ('krynki', '2011043', 'Krynki', 'podlaskie', 'puszcza-knyszynska', 2, 2),
  ('grodek', '2002042', 'Gródek', 'podlaskie', 'puszcza-knyszynska', 2, 3),
  ('hajnowka', '2005062', 'Hajnówka', 'podlaskie', 'puszcza-bialowieska', 2, 4),
  ('janow', '2011022', 'Janów', 'podlaskie', 'puszcza-knyszynska', 2, 5),
  ('sidra', '2011072', 'Sidra', 'podlaskie', 'lasy-podlasia', 2, 6),
  ('korycin', '2011032', 'Korycin', 'podlaskie', 'lasy-podlasia', 2, 7),
  ('knyszyn', '2008043', 'Knyszyn', 'podlaskie', 'puszcza-knyszynska', 3, 1),
  ('tykocin', '2002123', 'Tykocin', 'podlaskie', 'lasy-podlasia', 3, 2),
  ('narewka', '2005092', 'Narewka', 'podlaskie', 'puszcza-bialowieska', 3, 3),
  ('michalowo', '2002073', 'Michałowo', 'podlaskie', 'puszcza-knyszynska', 3, 4),
  ('suprasl', '2002093', 'Supraśl', 'podlaskie', 'puszcza-knyszynska', 3, 5),
  ('lapy', '2002063', 'Łapy', 'podlaskie', 'lasy-podlasia', 3, 6),
  ('turosn-koscielna', '2002112', 'Turośń Kościelna', 'podlaskie', 'lasy-podlasia', 3, 7),
  ('zawady', '2002152', 'Zawady', 'podlaskie', 'lasy-podlasia', 4, 2),
  ('narew', '2005082', 'Narew', 'podlaskie', 'puszcza-bialowieska', 4, 3),
  ('bocki', '2003042', 'Boćki', 'podlaskie', 'lasy-podlasia', 4, 4),
  ('orla', '2003062', 'Orla', 'podlaskie', 'lasy-podlasia', 4, 5),
  ('wyszki', '2003082', 'Wyszki', 'podlaskie', 'lasy-podlasia', 4, 6),
  ('bransk', '2003052', 'Brańsk', 'podlaskie', 'lasy-podlasia', 5, 1),
  ('bielsk-podlaski', '2003032', 'Bielsk Podlaski', 'podlaskie', 'lasy-podlasia', 5, 2),
  ('czeremcha', '2005032', 'Czeremcha', 'podlaskie', 'puszcza-bialowieska', 5, 3),
  ('milejczyce', '2010062', 'Milejczyce', 'podlaskie', 'lasy-podlasia', 5, 4),
  ('nurzec-stacja', '2010072', 'Nurzec-Stacja', 'podlaskie', 'lasy-podlasia', 5, 5),
  ('siemiatycze', '2010092', 'Siemiatycze', 'podlaskie', 'lasy-podlasia', 6, 2),
  ('drohiczyn', '2010023', 'Drohiczyn', 'podlaskie', 'lasy-podlasia', 6, 3),
  ('mielnik', '2010052', 'Mielnik', 'podlaskie', 'lasy-podlasia', 6, 4)
on conflict (id) do nothing;

insert into public.species (id, atlas_no, name, latin, short_name, rarity, edibility, habitat, clustered, typical_cap_cm, typical_height_cm, typical_weight_g) values
  ('borowik-szlachetny', 1, 'Borowik szlachetny', 'Boletus edulis', 'borowik', 'rzadki', 'jadalny', 'Las iglasty', false, 12, 14, 320),
  ('podgrzybek-brunatny', 2, 'Podgrzybek brunatny', 'Imleria badia', 'podgrzybek', 'pospolity', 'jadalny', 'Las iglasty', false, 9, 10, 120),
  ('czubajka-kania', 3, 'Czubajka kania', 'Macrolepiota procera', 'kania', 'epicki', 'jadalny', 'Polany i skraje lasu', false, 24, 28, 220),
  ('muchomor-czerwony', 4, 'Muchomor czerwony', 'Amanita muscaria', 'muchomor', 'pospolity', 'trujacy', 'Las mieszany', false, 13, 16, 180),
  ('pieprznik-jadalny', 5, 'Pieprznik jadalny (kurka)', 'Cantharellus cibarius', 'kurka', 'pospolity', 'jadalny', 'Las mieszany', true, 5, 6, 14),
  ('mleczaj-rydz', 6, 'Mleczaj rydz', 'Lactarius deliciosus', 'rydz', 'rzadki', 'jadalny', 'Młode bory sosnowe', false, 8, 6, 90),
  ('szmaciak-galezisty', 7, 'Szmaciak gałęzisty', 'Sparassis crispa', 'szmaciak', 'legendarny', 'jadalny', 'U podstawy sosen', false, 30, 20, 1400),
  ('muchomor-zielonawy', 8, 'Muchomor zielonawy', 'Amanita phalloides', 'muchomor', 'rzadki', 'smiertelny', 'Lasy liściaste', false, 9, 12, 90),
  ('smardz-jadalny', 9, 'Smardz jadalny', 'Morchella esculenta', 'smardz', 'epicki', 'jadalny', 'Wiosną, łęgi', false, 6, 10, 60),
  ('maslak-zwyczajny', 10, 'Maślak zwyczajny', 'Suillus luteus', 'maślak', 'pospolity', 'jadalny', 'Bory sosnowe', false, 8, 7, 70),
  ('kozlarz-babka', 11, 'Koźlarz babka', 'Leccinum scabrum', 'koźlarz', 'pospolity', 'jadalny', 'Pod brzozami', false, 9, 13, 110),
  ('kozlarz-czerwony', 12, 'Koźlarz czerwony', 'Leccinum aurantiacum', 'koźlarz', 'rzadki', 'jadalny', 'Pod osikami', false, 12, 15, 190),
  ('soplowka-jezowata', 13, 'Soplówka jeżowata', 'Hericium erinaceus', 'soplówka', 'legendarny', 'jadalny', 'Stare buki i dęby', false, 20, 15, 600),
  ('gaska-zielonka', 14, 'Gąska zielonka', 'Tricholoma equestre', 'gąska', 'pospolity', 'niejadalny', 'Piaszczyste bory', false, 8, 7, 60),
  ('opienka-miodowa', 15, 'Opieńka miodowa', 'Armillaria mellea', 'opieńka', 'pospolity', 'jadalny', 'Pnie i korzenie', true, 6, 9, 25),
  ('piestrzenica-kasztanowata', 16, 'Piestrzenica kasztanowata', 'Gyromitra esculenta', 'piestrzenica', 'rzadki', 'smiertelny', 'Wiosną, bory', false, 8, 9, 70),
  ('purchawka-chropowata', 17, 'Purchawka chropowata', 'Lycoperdon perlatum', 'purchawka', 'pospolity', 'jadalny', 'Ściółka leśna', false, 4, 6, 30),
  ('golabek-zielonawy', 18, 'Gołąbek zielonawy', 'Russula virescens', 'gołąbek', 'rzadki', 'jadalny', 'Buczyny i dąbrowy', false, 10, 8, 110),
  ('zagwica-listkowata', 19, 'Żagwica listkowata', 'Grifola frondosa', 'żagwica', 'epicki', 'jadalny', 'U podstawy dębów', false, 25, 18, 900),
  ('goryczak-zolciowy', 20, 'Goryczak żółciowy', 'Tylopilus felleus', 'goryczak', 'pospolity', 'niejadalny', 'Las iglasty', false, 10, 11, 150),
  ('borowik-ceglastopory', 21, 'Borowik ceglastopory', 'Neoboletus erythropus', 'ceglasty', 'rzadki', 'jadalny', 'Bory świerkowe', false, 12, 12, 250),
  ('muchomor-plamisty', 22, 'Muchomor plamisty', 'Amanita pantherina', 'muchomor', 'pospolity', 'trujacy', 'Lasy mieszane', false, 9, 11, 90),
  ('borowik-krolewski', 23, 'Borowik królewski', 'Butyriboletus regius', 'królewski', 'legendarny', 'jadalny', 'Ciepłe buczyny', false, 14, 12, 380),
  ('plachetka-zwyczajna', 24, 'Płachetka zwyczajna', 'Cortinarius caperatus', 'płachetka', 'pospolity', 'jadalny', 'Bory sosnowe', false, 9, 11, 80),
  ('czernidlak-kolpakowaty', 25, 'Czernidłak kołpakowaty', 'Coprinus comatus', 'czernidłak', 'pospolity', 'jadalny', 'Łąki i pobocza', false, 5, 15, 50),
  ('zaslonak-rudy', 26, 'Zasłonak rudy', 'Cortinarius orellanus', 'zasłonak', 'epicki', 'smiertelny', 'Lasy liściaste', false, 6, 8, 35),
  ('sarniak-dachowkowaty', 27, 'Sarniak dachówkowaty', 'Sarcodon imbricatus', 'sarniak', 'rzadki', 'jadalny', 'Bory świerkowe', false, 15, 8, 260),
  ('maslak-sitarz', 28, 'Maślak sitarz', 'Suillus bovinus', 'sitarz', 'pospolity', 'jadalny', 'Bory sosnowe', true, 6, 5, 40),
  ('kozlarz-pomaranczowozolty', 29, 'Koźlarz pomarańczowożółty', 'Leccinum versipelle', 'koźlarz', 'rzadki', 'jadalny', 'Pod brzozami', false, 13, 16, 210),
  ('lejkowiec-dety', 30, 'Lejkowiec dęty', 'Craterellus cornucopioides', 'lejkowiec', 'rzadki', 'jadalny', 'Buczyny', true, 5, 8, 12),
  ('mleczaj-smaczny', 31, 'Mleczaj smaczny', 'Lactarius volemus', 'mleczaj', 'rzadki', 'jadalny', 'Lasy mieszane', false, 10, 9, 120),
  ('siedzun-sosnowy', 32, 'Siedzuń sosnowy', 'Sparassis nemecii', 'siedzuń', 'epicki', 'jadalny', 'Stare sosny', false, 22, 16, 700),
  ('borowik-szatanski', 33, 'Borowik szatański', 'Rubroboletus satanas', 'szatan', 'epicki', 'trujacy', 'Wapienne buczyny', false, 18, 12, 450),
  ('lakowka-ametystowa', 34, 'Lakówka ametystowa', 'Laccaria amethystina', 'lakówka', 'pospolity', 'jadalny', 'Lasy mieszane', true, 4, 6, 8),
  ('gaska-siarkowa', 35, 'Gąska siarkowa', 'Tricholoma sulphureum', 'gąska', 'pospolity', 'niejadalny', 'Lasy liściaste', false, 6, 7, 40),
  ('strzepiak-ceglasty', 36, 'Strzępiak ceglasty', 'Inocybe erubescens', 'strzępiak', 'rzadki', 'smiertelny', 'Parki i buczyny', false, 6, 8, 30)
on conflict (id) do nothing;

insert into public.species_lookalikes (species_id, lookalike_name, lookalike_id, lookalike_edibility, tip) values
  ('borowik-szlachetny', 'goryczak żółciowy', 'goryczak-zolciowy', 'niejadalny', 'Sprawdź siateczkę na trzonie i kolor rurek.'),
  ('podgrzybek-brunatny', 'goryczak żółciowy', 'goryczak-zolciowy', 'niejadalny', 'Goryczak ma różowawe rurki i ciemną siateczkę na trzonie.'),
  ('czubajka-kania', 'muchomor sromotnikowy', null, 'smiertelny', 'Kania ma ruchomy pierścień i wężykowaty wzór na trzonie, bez pochwy u podstawy.'),
  ('pieprznik-jadalny', 'lisówka pomarańczowa', null, 'niejadalny', 'Kurka ma grube, rozwidlone listewki zamiast cienkich blaszek.'),
  ('mleczaj-rydz', 'mleczaj wełnianka', null, 'trujacy', 'Rydz wydziela pomarańczowe mleczko; wełnianka – białe i ma kosmaty brzeg.'),
  ('smardz-jadalny', 'piestrzenica kasztanowata', 'piestrzenica-kasztanowata', 'smiertelny', 'Smardz ma pusty w środku owocnik i regularne komory na kapeluszu.'),
  ('golabek-zielonawy', 'muchomor zielonawy', 'muchomor-zielonawy', 'smiertelny', 'Gołąbek nie ma pierścienia ani pochwy u podstawy trzonu.'),
  ('goryczak-zolciowy', 'borowik szlachetny', 'borowik-szlachetny', 'jadalny', 'Goryczak ma różowe rurki i ciemną siateczkę.'),
  ('borowik-ceglastopory', 'borowik szatański', 'borowik-szatanski', 'trujacy', 'Szatan ma biały kapelusz i siateczkę na trzonie – ceglastopory jest kropkowany.')
on conflict do nothing;

insert into public.badges (id, name, description, icon, color, icon_color, sort, rule) values
  ('krol-puszczy', 'Król Puszczy', '10 borowików w Puszczy Knyszyńskiej', 'military_tech', '#EFA831', '#4A3200', 0, '{"type":"species_in_region","species":"borowik-szlachetny","region":"puszcza-knyszynska","count":10}'),
  ('ranny-ptaszek', 'Ranny ptaszek', 'Wyprawa rozpoczęta przed 6:00', 'wb_twilight', '#2B99E7', '#0E2442', 1, '{"type":"early_bird","before":"06:00"}'),
  ('km-100', '100 km', '100 km przebytych na wyprawach', 'hiking', '#7FB547', '#1F3310', 2, '{"type":"distance_km","km":100}'),
  ('seria-7', 'Seria 7 dni', '7 dni z rzędu w lesie', 'local_fire_department', '#A56CDE', '#2A0D3A', 3, '{"type":"streak","days":7}'),
  ('lowca-legend', 'Łowca Legend', 'Znajdź gatunek legendarny', 'diamond', '#EFA831', '#4A3200', 4, '{"type":"rarity_find","rarity":"legendarny","count":1}')
on conflict (id) do nothing;

insert into public.quest_templates (id, kind, title, icon, icon_filled, icon_bg, icon_color, xp, target, sort) values
  ('q-scan-5', 'scans', 'Zeskanuj 5 grzybów', 'photo_camera', false, '#EEF5E3', '#4C7A22', 100, 5, 0),
  ('q-rare-1', 'rare', 'Znajdź rzadki gatunek', 'diamond', true, '#E9EEF9', '#0068B2', 150, 1, 1),
  ('q-km-5', 'distance', 'Przejdź 5 km', 'hiking', false, '#FFF0DD', '#A2560F', 80, 5, 2)
on conflict (id) do nothing;

insert into public.gmina_challenges (gmina_id, species_id, title, description, xp, badge_id)
select 'suprasl', 'szmaciak-galezisty', 'Znajdź szmaciaka gałęzistego', 'Tylko 4 osoby znalazły go tu w tym sezonie.', 500, 'lowca-legend'
where not exists (select 1 from public.gmina_challenges where gmina_id = 'suprasl' and species_id = 'szmaciak-galezisty');

insert into public.achievements (id, category, name, icon, metric, params, secret, sort) values
  ('kolekcjoner', 'kolekcja', 'Kolekcjoner', 'menu_book', 'species', '{}', false, 0),
  ('smakosz', 'kolekcja', 'Smakosz', 'restaurant', 'species', '{"edibility":"jadalne"}', false, 1),
  ('lowca-rzadkosci', 'kolekcja', 'Łowca rzadkości', 'diamond', 'species', '{"rarity":"rzadki"}', false, 2),
  ('epicka-kolekcja', 'kolekcja', 'Epicka kolekcja', 'stars', 'species', '{"rarity":"epicki"}', false, 3),
  ('legenda-lasu', 'kolekcja', 'Legenda lasu', 'award_star', 'species', '{"rarity":"legendarny"}', false, 4),
  ('wielka-trojka', 'zestawy', 'Wielka trójka', 'workspace_premium', 'set', '{}', false, 5),
  ('borowiki-i-spolka', 'zestawy', 'Borowiki i spółka', 'forest', 'set', '{}', false, 6),
  ('pod-brzoza', 'zestawy', 'Pod brzozą i osiką', 'landscape', 'set', '{}', false, 7),
  ('krolewska-rodzina', 'zestawy', 'Królewska rodzina', 'trophy', 'set', '{}', false, 8),
  ('kurki-i-rydze', 'zestawy', 'Kurki, rydze i gołąbki', 'local_florist', 'set', '{}', false, 9),
  ('lesne-dziwy', 'zestawy', 'Leśne dziwy', 'filter_vintage', 'set', '{}', false, 10),
  ('wiosenny-zwiadowca', 'zestawy', 'Wiosenny zwiadowca', 'spa', 'set', '{}', false, 11),
  ('muchomory', 'zestawy', 'Muchomory bez tajemnic', 'visibility', 'set', '{}', false, 12),
  ('znam-wroga', 'bezpieczenstwo', 'Znam wroga', 'shield', 'species', '{"edibility":"trujace"}', false, 13),
  ('spotkanie-ze-smiercia', 'bezpieczenstwo', 'Spotkanie ze śmiercią', 'skull', 'species', '{"edibility":"smiertelne"}', false, 14),
  ('mistrz-sobowtorow', 'bezpieczenstwo', 'Mistrz sobowtórów', 'health_and_safety', 'lookalike_pairs', '{}', false, 15),
  ('pelny-koszyk', 'okazy', 'Pełny koszyk', 'shopping_basket', 'specimens', '{}', false, 16),
  ('specjalista', 'okazy', 'Specjalista', 'school', 'max_of_species', '{}', false, 17),
  ('znawca', 'okazy', 'Znawca', 'auto_stories', 'species_with_count', '{"min":5}', false, 18),
  ('okazy-xxl', 'okazy', 'Okazy XXL', 'egg', 'xxl_finds', '{}', false, 19),
  ('parasol', 'okazy', 'Parasol', 'straighten', 'record', '{"species":"czubajka-kania","field":"best_cap_cm"}', false, 20),
  ('kilogramowy-borowik', 'okazy', 'Kilogramowy borowik', 'scale', 'record', '{"species":"borowik-szlachetny","field":"best_weight_g"}', false, 21),
  ('diabelski-borowik', 'sekretne', 'Diabelski borowik', 'local_fire_department', 'set', '{}', true, 22),
  ('biala-broda', 'sekretne', 'Biała broda', 'water_drop', 'set', '{}', true, 23)
on conflict (id) do update set category = excluded.category, name = excluded.name, icon = excluded.icon,
  metric = excluded.metric, params = excluded.params, secret = excluded.secret, sort = excluded.sort;

insert into public.achievement_tiers (achievement_id, tier, target, xp, medal, goal) values
  ('kolekcjoner', 1, 10, 50, 'braz', 'Odkryj 10 gatunków w atlasie'),
  ('kolekcjoner', 2, 25, 100, 'srebro', 'Odkryj 25 gatunków w atlasie'),
  ('kolekcjoner', 3, 50, 250, 'zloto', 'Odkryj 50 gatunków w atlasie'),
  ('kolekcjoner', 4, 100, 500, 'platyna', 'Odkryj 100 gatunków w atlasie'),
  ('smakosz', 1, 5, 50, 'braz', 'Odkryj 5 gatunków jadalnych'),
  ('smakosz', 2, 15, 100, 'srebro', 'Odkryj 15 gatunków jadalnych'),
  ('smakosz', 3, 30, 250, 'zloto', 'Odkryj 30 gatunków jadalnych'),
  ('lowca-rzadkosci', 1, 3, 75, 'braz', 'Odkryj 3 gatunki rzadkie'),
  ('lowca-rzadkosci', 2, 6, 150, 'srebro', 'Odkryj 6 gatunków rzadkich'),
  ('lowca-rzadkosci', 3, 10, 300, 'zloto', 'Odkryj 10 gatunków rzadkich'),
  ('epicka-kolekcja', 1, 1, 100, 'braz', 'Odkryj 1 gatunek epicki'),
  ('epicka-kolekcja', 2, 3, 250, 'srebro', 'Odkryj 3 gatunki epickie'),
  ('epicka-kolekcja', 3, 5, 500, 'zloto', 'Odkryj 5 gatunków epickich'),
  ('legenda-lasu', 1, 1, 300, 'srebro', 'Odkryj gatunek legendarny'),
  ('legenda-lasu', 2, 3, 1000, 'zloto', 'Odkryj 3 legendy lasu'),
  ('wielka-trojka', 1, 3, 150, 'zloto', 'Borowik, kania i kurka w atlasie'),
  ('borowiki-i-spolka', 1, 11, 400, 'zloto', 'Wszystkie grzyby rurkowe z katalogu'),
  ('pod-brzoza', 1, 3, 150, 'zloto', 'Trzy koźlarze: babka, czerwony i pomarańczowożółty'),
  ('krolewska-rodzina', 1, 4, 300, 'zloto', 'Cztery borowiki – od szlachetnego po szatańskiego'),
  ('kurki-i-rydze', 1, 5, 200, 'zloto', 'Pięć gatunków blaszkowych na patelnię'),
  ('lesne-dziwy', 1, 5, 400, 'zloto', 'Grzyby z pni i korzeni – od opieńki po soplówkę'),
  ('wiosenny-zwiadowca', 1, 2, 200, 'zloto', 'Smardz i piestrzenica – wiosenna para'),
  ('muchomory', 1, 3, 150, 'zloto', 'Sfotografuj trzy muchomory'),
  ('znam-wroga', 1, 1, 50, 'braz', 'Sfotografuj 1 gatunek trujący'),
  ('znam-wroga', 2, 3, 100, 'srebro', 'Sfotografuj 3 gatunki trujące'),
  ('znam-wroga', 3, 6, 250, 'zloto', 'Sfotografuj 6 gatunków trujących'),
  ('spotkanie-ze-smiercia', 1, 1, 100, 'srebro', 'Sfotografuj gatunek śmiertelnie trujący'),
  ('spotkanie-ze-smiercia', 2, 4, 400, 'zloto', 'Sfotografuj 4 gatunki śmiertelnie trujące'),
  ('mistrz-sobowtorow', 1, 2, 100, 'srebro', 'Odkryj 2 pary: gatunek i jego sobowtór'),
  ('mistrz-sobowtorow', 2, 5, 300, 'zloto', 'Odkryj 5 par: gatunek i jego sobowtór'),
  ('pelny-koszyk', 1, 100, 50, 'braz', 'Zbierz 100 okazów do atlasu'),
  ('pelny-koszyk', 2, 250, 100, 'srebro', 'Zbierz 250 okazów do atlasu'),
  ('pelny-koszyk', 3, 500, 250, 'zloto', 'Zbierz 500 okazów do atlasu'),
  ('pelny-koszyk', 4, 1000, 500, 'platyna', 'Zbierz 1000 okazów do atlasu'),
  ('specjalista', 1, 10, 50, 'braz', 'Znajdź 10 okazów jednego gatunku'),
  ('specjalista', 2, 25, 100, 'srebro', 'Znajdź 25 okazów jednego gatunku'),
  ('specjalista', 3, 50, 200, 'zloto', 'Znajdź 50 okazów jednego gatunku'),
  ('specjalista', 4, 100, 400, 'platyna', 'Znajdź 100 okazów jednego gatunku'),
  ('znawca', 1, 5, 75, 'braz', 'Znajdź 5 gatunków co najmniej po 5 razy'),
  ('znawca', 2, 10, 150, 'srebro', 'Znajdź 10 gatunków co najmniej po 5 razy'),
  ('znawca', 3, 20, 300, 'zloto', 'Znajdź 20 gatunków co najmniej po 5 razy'),
  ('okazy-xxl', 1, 1, 50, 'braz', 'Znajdź okaz XXL'),
  ('okazy-xxl', 2, 5, 150, 'srebro', 'Znajdź 5 okazów XXL'),
  ('okazy-xxl', 3, 15, 400, 'zloto', 'Znajdź 15 okazów XXL'),
  ('parasol', 1, 30, 200, 'zloto', 'Kania z kapeluszem co najmniej 30 cm'),
  ('kilogramowy-borowik', 1, 1000, 300, 'zloto', 'Borowik szlachetny ważący co najmniej 1 kg'),
  ('diabelski-borowik', 1, 1, 250, 'zloto', 'Sfotografuj borowika szatańskiego'),
  ('biala-broda', 1, 1, 400, 'zloto', 'Znajdź soplówkę jeżowatą')
on conflict (achievement_id, tier) do update set target = excluded.target, xp = excluded.xp, medal = excluded.medal, goal = excluded.goal;

insert into public.achievement_set_species (achievement_id, species_id) values
  ('wielka-trojka', 'borowik-szlachetny'),
  ('wielka-trojka', 'czubajka-kania'),
  ('wielka-trojka', 'pieprznik-jadalny'),
  ('borowiki-i-spolka', 'borowik-szlachetny'),
  ('borowiki-i-spolka', 'podgrzybek-brunatny'),
  ('borowiki-i-spolka', 'borowik-ceglastopory'),
  ('borowiki-i-spolka', 'borowik-krolewski'),
  ('borowiki-i-spolka', 'borowik-szatanski'),
  ('borowiki-i-spolka', 'goryczak-zolciowy'),
  ('borowiki-i-spolka', 'kozlarz-babka'),
  ('borowiki-i-spolka', 'kozlarz-czerwony'),
  ('borowiki-i-spolka', 'kozlarz-pomaranczowozolty'),
  ('borowiki-i-spolka', 'maslak-zwyczajny'),
  ('borowiki-i-spolka', 'maslak-sitarz'),
  ('pod-brzoza', 'kozlarz-babka'),
  ('pod-brzoza', 'kozlarz-czerwony'),
  ('pod-brzoza', 'kozlarz-pomaranczowozolty'),
  ('krolewska-rodzina', 'borowik-szlachetny'),
  ('krolewska-rodzina', 'borowik-ceglastopory'),
  ('krolewska-rodzina', 'borowik-krolewski'),
  ('krolewska-rodzina', 'borowik-szatanski'),
  ('kurki-i-rydze', 'pieprznik-jadalny'),
  ('kurki-i-rydze', 'lejkowiec-dety'),
  ('kurki-i-rydze', 'mleczaj-rydz'),
  ('kurki-i-rydze', 'mleczaj-smaczny'),
  ('kurki-i-rydze', 'golabek-zielonawy'),
  ('lesne-dziwy', 'opienka-miodowa'),
  ('lesne-dziwy', 'siedzun-sosnowy'),
  ('lesne-dziwy', 'zagwica-listkowata'),
  ('lesne-dziwy', 'szmaciak-galezisty'),
  ('lesne-dziwy', 'soplowka-jezowata'),
  ('wiosenny-zwiadowca', 'smardz-jadalny'),
  ('wiosenny-zwiadowca', 'piestrzenica-kasztanowata'),
  ('muchomory', 'muchomor-czerwony'),
  ('muchomory', 'muchomor-plamisty'),
  ('muchomory', 'muchomor-zielonawy'),
  ('diabelski-borowik', 'borowik-szatanski'),
  ('biala-broda', 'soplowka-jezowata')
on conflict do nothing;

-- Gracze z istniejącym atlasem: już osiągnięte stopnie bez wypłaty XP (przy pustej bazie nic nie robi).
select public.seed_achievements(id) from public.profiles;
